name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Instalação do Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Instala dependências
      - name: Install dependencies
        run: flutter pub get

      # Análise do código (NÃO falha por warnings)
      - name: Analyze project source
        run: flutter analyze --no-fatal-warnings || true

      # Executa testes
      - name: Run tests
        run: flutter test
